name: Selenium Test

on:
  workflow_dispatch:

jobs:
  selenium-job:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      
      - name: Install Selenium dependencies
        run: |
          pip install selenium

      - name: Install Chrome browser
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run Selenium script
        run: |
          python autonews.py

      - uses: stefanzweifel/git-auto-commit-action@v5
        id: auto-commit-action
        with:
            commit_message: Changed files
            branch: ${{ github.ref }}
            force: true
